# Generated by Django 3.0.3 on 2020-03-31 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='release_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='developer',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='developer',
            name='register_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='release_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='register_time',
            field=models.DateField(),
        ),
    ]
