# Generated by Django 3.0.3 on 2020-03-31 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('chId', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.BooleanField(default=0)),
                ('title', models.CharField(max_length=100)),
                ('requirment', models.TextField()),
                ('award', models.IntegerField(default=0)),
                ('viewer_num', models.IntegerField(default=0)),
                ('release_time', models.TimeField()),
                ('status', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('deveId', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.BooleanField(default=0)),
                ('devename', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('deveage', models.IntegerField(default=1)),
                ('email', models.CharField(max_length=20)),
                ('frame', models.IntegerField(default=100)),
                ('register_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('taskId', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.BooleanField(default=1)),
                ('title', models.CharField(max_length=100)),
                ('requirment', models.TextField()),
                ('viewer_num', models.IntegerField(default=0)),
                ('release_time', models.TimeField()),
                ('status', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.BooleanField(default=1)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('userage', models.IntegerField(default=1)),
                ('email', models.CharField(max_length=20)),
                ('frame', models.IntegerField(default=50)),
                ('register_time', models.TimeField()),
            ],
        ),
    ]
