# Generated by Django 3.0.3 on 2020-04-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20200401_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='frame',
            field=models.IntegerField(default=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='register_time',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.BooleanField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userage',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
