# Generated by Django 3.0.3 on 2020-04-01 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_auto_20200401_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='frame',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='userage',
            field=models.IntegerField(default=1),
        ),
    ]
