# Generated by Django 3.0.3 on 2020-04-09 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0008_auto_20200401_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='hoster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.User'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='release_time',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='register_time',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='release_time',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='register_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
